### PR TITLE
Set private recipe repo as .env parameter

### PR DESCRIPTION
**Pull request by Lo-X**
Hi,
Nice project, we needed it with my company to have our own recipes kept private!
While testing it and installing it, I noticed the private repo (and to some extent, other configurations) were straight in the `services.yaml` file. The parameters change on each installation and for each developer, so I allowed myself to move the private repo url in the DotEnv (`.env.dist`) file instead so that : 
- We don't need to commit it
- We don't have problems on further updates / git pulls

Hope this is useful. Have a nice day.

### CODE REVIEW

**Comment by moay** [comment]
Hi! Thanks for your contribution.

I get your thought, but I think this is not thought through yet. The other parameters for server configuration (like proxying yes/no, mirroring yes/no, etc.) are as much variable as the private recipe repo url is. So I would like to have a solution that will solve the problem for the entirety of those settings.

Using the .env files has an additional drawback as it imposes using environment variables for your configurations which is debatable.

I'll think this through and reconsider your PR in the next days. Feel free to discuss on the issue, I'd love to hear your thoughts.

**Comment by Lo-X** [comment]
Yes, the other variables should be in a configuration too. All of these can change from one environment to another. We can agree on that. 

How should these be configured is another matter. Sure they can be put in some kind of `parameters.yaml(.dist)` and it would be easy to install them with Incenteev. Just like with a Symfony 2 project. No `.env` nor environment variable involved.

That beeing said, you're using a Symfony 4 skeleton and Symfony 4 guidelines and Fabier Potencier's advice are to use environment variables. After all, it is their purpose. I guess that people will be used to them pretty fast using Symfony 4 and they won't use a private flex server unless they already are using Symfony 4. It would not be harder for them that any other project they might have worked on.

**Comment by moay** [comment]
Yes, having some sort of `parameters.yaml.dist` is a solution that I considered. I am aware of the general recommendation of using environment variables, but we have been discussing this issue at our company and our sysadmins pointed out that this is not a secure way to store settings. In this case there is nothing too sensitive that will be stored but we won't be able to use environment variables at all on our production hostings.

Apart from our company this should be a decision on a project base and independent from our hosting setups. 

Maybe allowing a fallback if no environment variable is found could be a proper solution. I'll think of it.

**Comment by moay** [comment]
All string configs will now be configurable via env variables, also there is a `parameters.yaml` for the configuration. Thanks for the input!

**Pull request closed without merging**
